{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "transfer.sh.fullname" . }}
  labels:
    {{- include "transfer.sh.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "transfer.sh.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- if .Values.networkPolicy.ingressNamespace }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace }}
      ports:
        - port: 8080
          protocol: TCP
    {{- else }}
    - {}
    {{- end }}
    {{- with .Values.networkPolicy.additionalIngressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
